# Generated by Django 3.0.6 on 2021-08-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessangerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
