# Generated by Django 3.0.6 on 2021-08-28 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MessangerApp', '0003_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='msgs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MessangerApp.Message'),
        ),
    ]
